 apiVersion: 1

 datasources:
   - name: Loki (Observability Platform)
     type: loki
     uid: loki-platform
     access: proxy
     orgId: 1
     url: http://host.docker.internal/query/v1/logs/
     isDefault: false
     editable: true