 apiVersion: 1

 datasources:
   - name: Tempo (Observability Platform)
     type: tempo
     uid: tempo-platform
     access: proxy
     orgId: 1
     url: http://host.docker.internal/query/v1/traces/
     basicAuth: false
     isDefault: false
     version: 1
     editable: true
     apiVersion: 1
     jsonData:
       httpMethod: GET
       serviceMap:
         datasourceUid: prometheus-platform